<?php

/**
 * @file
 * Primary module hooks for Media Album AV - Common module.
 */

/**
 * Implements hook_theme().
 */
function media_album_av_common_theme($existing, $type, $theme, $path) {
  return [
    'media_light_table' => [
      'variables' => [
      'theme' => [],
      'view' => [],
      'options' => [],
      'groups' => [],
      ],
      'path' => $path . '/templates',
      'template' => 'media-light-table',
    ],
  ];
}

